# HITO - Toolset
# Autor: Sebastian Stäubert <sebastian.staeubert@imise.uni-leipzig.de>
# Changes from Konrad Höffner <konrad.hoeffner@imise.uni-leipzig.de>

version: '3'

services:

# Virtuoso:
#   Access via http://<hostname>:8080
#   Access vio iSQL://localhost:1111

#  virtuoso:
#    image: tenforce/virtuoso:latest
#    environment:
#      DBA_PASSWORD: ${DBA_PASSWORD}
#      SPARQL_UPDATE: 'true'
#      DEFAULT_GRAPH: 'http://www.snik.eu/ontology'
#    volumes:
#      - /usr/local/virtuoso-opensource/lib
#      - virtuoso-data:/data
#    ports:
#      - "127.0.0.1:8102:8890"
#      - "127.0.0.1:8103:1111"
#    restart: unless-stopped

# LodView
#   Access via http://<hostname>:8889
#  lodview:
#    build: ./lodview
#    ports:
#      - "127.0.0.1:8104:8080"
#    links:
#      - virtuoso
#    restart: unless-stopped

## TripleCheckMate
##   Access via http://<hostname>:8888
#  triplecheckmate:
#    build: ./TripleCheckMate
#    ports:
#      - "8888:8080"
#    links:
#      - virtuoso
#    restart: unless-stopped

  sparqltosql:
    build: .
    #depends_on:
    #  - virtuoso
    #environment:
    #  - HITO_SPARQL_ENDPOINT=localhost:...
    #  - DBPEDIA_SPARQL_ENDPOINT= 
    volumes:
      - sql:/sql

  postgresql:
    # upgrade to postgresql 14 when available for Arch Linux for local testing
    image: bitnami/postgresql:13
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - sql:/docker-entrypoint-initdb.d
      #- /path/to/postgresql-persistence:/bitnami/postgresql
    depends_on:
      - sparqltosql

  phppgadmin:
    #restart: unless-stopped
    #image: dockage/phppgadmin:latest
    image: bitnami/phppgadmin:latest
    ports:
      - "127.0.0.1:8111:8080"
      #- "443:443"
      #- '80:8080'
    depends_on:
      - postgresql
    #environment:
    #- PHP_PG_ADMIN_SERVER_DESC=PostgreSQL
    #- PHP_PG_ADMIN_SERVER_HOST=postgres
    #- PHP_PG_ADMIN_SERVER_PORT=5432
    #- PHP_PG_ADMIN_SERVER_SSL_MODE=allow
    #- PHP_PG_ADMIN_SERVER_DEFAULT_DB=postgres
    #- PHP_PG_ADMIN_SERVER_PG_DUMP_PATH=/usr/bin/pg_dump
    #- PHP_PG_ADMIN_SERVER_PG_DUMPALL_PATH=/usr/bin/pg_dumpall

    #- PHP_PG_ADMIN_DEFAULT_LANG=auto
    #- PHP_PG_ADMIN_AUTO_COMPLETE=default on
    #- PHP_PG_ADMIN_EXTRA_LOGIN_SECURITY=false
    #- PHP_PG_ADMIN_OWNED_ONLY=false
    #- PHP_PG_ADMIN_SHOW_COMMENTS=true
    #- PHP_PG_ADMIN_SHOW_ADVANCED=false
    #- PHP_PG_ADMIN_SHOW_SYSTEM=false
    #- PHP_PG_ADMIN_MIN_PASSWORD_LENGTH=8
    #- PHP_PG_ADMIN_LEFT_WIDTH=200
    #- PHP_PG_ADMIN_THEME=default
    #- PHP_PG_ADMIN_SHOW_OIDS=false
    #- PHP_PG_ADMIN_MAX_ROWS=30
    #- PHP_PG_ADMIN_MAX_CHARS=50
    #- PHP_PG_ADMIN_USE_XHTML_STRICT=false
    #- PHP_PG_ADMIN_HELP_BASE=http://www.postgresql.org/docs/%s/interactive/
    #- PHP_PG_ADMIN_AJAX_REFRESH=3

  database-frontend:
    restart: unless-stopped
    build: ../database-frontend
    depends_on:
      - postgresql
    ports:
      - "8112:5000"
    environment:
      - HITO_DATABASE_HOST=postgresql
      - HITO_DATABASE_PORT=5432
      - HITO_DATABASE_PASSWORD=${POSTGRESQL_PASSWORD}
      - HITO_DATABASE_NAME=postgres
      #- HITO_DATABASE_FRONTEND_SERVER_NAME=bruchtal.imise.uni-leipzig.de/database-frontend

#networks:
#  default:
#    ipam:
#      driver: default
#      config:
#         - subnet: 172.23.13.0/24
#           ip_range: 172.23.13.0/24
#           gateway: 172.23.13.254

volumes:
  virtuoso-data:
  postgres-data:
  sql:

